// Lists every third-party package that ends up inside the shipped bundles
// (from esbuild's metafile, so only code that is really included), checks the
// licences are ones we can ship, and writes THIRD_PARTY_NOTICES.md with each
// licence text, as MIT, ISC and similar licences require.
// Usage: node scripts/notices.mjs [--check]   (--check: fail if the file is out of date)
import * as esbuild from 'esbuild';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const allowed = new Set(['MIT', 'ISC', 'BSD-2-Clause', 'BSD-3-Clause', 'Apache-2.0', '0BSD']);

const common = {
  bundle: true,
  write: false,
  metafile: true,
  logLevel: 'silent',
  absWorkingDir: root,
};
const results = await Promise.all([
  esbuild.build({
    ...common,
    entryPoints: ['src/extension/extension.ts'],
    platform: 'node',
    format: 'cjs',
    external: ['vscode'],
    outdir: 'out-notices',
  }),
  esbuild.build({
    ...common,
    entryPoints: ['src/webview/main.tsx'],
    platform: 'browser',
    format: 'iife',
    jsx: 'automatic',
    outdir: 'out-notices',
  }),
]);

// node_modules/<name> or node_modules/@scope/<name>, from each bundled input path.
const packages = new Map();
for (const { metafile } of results) {
  for (const input of Object.keys(metafile.inputs)) {
    const parts = input.split(/[\\/]/);
    const at = parts.lastIndexOf('node_modules');
    if (at < 0) continue;
    const name = parts[at + 1]?.startsWith('@')
      ? `${parts[at + 1]}/${parts[at + 2]}`
      : parts[at + 1];
    const dir = join(root, ...parts.slice(0, at + 1), ...name.split('/'));
    packages.set(name, dir);
  }
}

const problems = [];
const entries = [...packages.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, dir]) => {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    const license = typeof pkg.license === 'string' ? pkg.license : JSON.stringify(pkg.license);
    if (!allowed.has(license)) problems.push(`${name}: ${license}`);
    const file = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
    const text = file
      ? readFileSync(join(dir, file), 'utf8').replace(/\r\n?/g, '\n').trim()
      : `${license} (no licence file in the package)`;
    return { name, version: pkg.version, license, text };
  });

const notices = [
  '# Third-party notices',
  '',
  'Prophasis bundles the following open-source packages into its extension and',
  'panel code. Their licences are reproduced below. Generated by',
  '`node scripts/notices.mjs`; do not edit by hand.',
  '',
  '| Package | Version | Licence |',
  '|---|---|---|',
  ...entries.map((e) => `| ${e.name} | ${e.version} | ${e.license} |`),
  '',
  ...entries.flatMap((e) => [
    `## ${e.name} ${e.version} (${e.license})`,
    '',
    '```text',
    e.text,
    '```',
    '',
  ]),
].join('\n');

for (const e of entries) console.log(`${e.license.padEnd(12)} ${e.name}@${e.version}`);
if (problems.length) {
  console.error(`Licences not on the allowed list:\n  ${problems.join('\n  ')}`);
  process.exit(1);
}

const target = join(root, 'THIRD_PARTY_NOTICES.md');
if (process.argv.includes('--check')) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== notices) {
    console.error('THIRD_PARTY_NOTICES.md is out of date: run node scripts/notices.mjs');
    process.exit(1);
  }
  console.log('THIRD_PARTY_NOTICES.md is up to date');
} else {
  writeFileSync(target, notices);
  console.log(
    `Wrote ${entries.length} packages to THIRD_PARTY_NOTICES.md (${sep === '\\' ? 'Windows' : 'POSIX'} paths ok)`,
  );
}
